# Generated by Django 4.2.5 on 2023-09-18 08:41

from django.db import migrations, models
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=225)),
                ('summary', models.CharField(max_length=335)),
                ('date', models.DateField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='update/', verbose_name='Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
