# Generated by Django 4.2.5 on 2023-09-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=250)),
                ('subaddress', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
            ],
        ),
    ]
