# Generated by Django 4.2.5 on 2023-09-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
    ]
