# Generated by Django 4.2.5 on 2023-10-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_checkout_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order_product',
        ),
    ]
