# Generated by Django 4.2.5 on 2023-09-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_product_product_del_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
